### ISSUE TITLE
Should this include the selection algorithm?

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#3]
Per https://github.com/w3c/manifest/pull/710, there was some discussion around a standardized selection algorithm that could be used by any spec that wants it (or replaced for spec that don’t). I know @rayankans felt that was outside the scope of this "dictionary" spec, but I wanted to flag it as a separate issue so we could discuss it in greater depth.

+ @mguica @marcoscaceres @jakearchibald @dominickng

**Comment by rayankans** [comment]
@mgiuca who Aaron meant to tag.

My 2c: Selection is heavily dependent on the environment the image will be displayed in. A generic enough algorithm would probably not be that useful, and potentially restrictive to the browser's UI. It's best left as a user agent decision to pick the appropriate resource.

**Comment by jakearchibald** [comment]
I think we can provide some selection rules that give the UA freedom whilst providing consistency. Eg, should the order matter?

**Comment by aarongustafson** [comment]
I think certain aspects of the `ImageResource` algorithm make sense to include, for instance

* Matching algorithm (as @jakearchibald mentioned) and
* URL resolution.

There may be others.

**Comment by mgiuca** [comment]
Which specs are we talking about that want it? My feeling is that this could get used in two places:

- Internal to the web platform rendering algorithm (e.g., hypothetically if an `<img>` element could refer to an ImageResource set, and the user agent should pick "the best" image based on the browser's current zoom level, etc). In these cases you would want to standardize the picking algorithm so that the document renders the same in all user agents.
- External to the web platform, e.g., for app icons in the manifest that are shown in the OS launchers. In these cases I think we very much _do not_ want to standardize the picking algorithm. The user agent and/or OS should be free to pick "the best" icon from the set, and that could mean different things in different contexts.

On that second point, in particular, most browsers will probably not implement a picking algorithm at all, they will convert _all_ icons into the host OS "icon family" format (e.g., on Windows bundle them all into a single .ico file; on Android convert them to the various sizes expected in an APK bundle), and then let the OS pick the best icon in its usual way. Therefore, we literally couldn't enforce a consistent picking algorithm unless we get all the OSes on board.

So if we do define an algorithm, it should only be used by the first type of context. Do we have any actual intended usages of this inside the web renderer itself?

> URL resolution.

URL resolution should definitely be part of the spec. It already is for ImageResource in the manifest spec. (Aside: I didn't realise this has already started. Any reason you're starting from scratch and not moving the text from the Manifest spec, where there is already a lot of existing infrastructure? Also, Bikeshed makes that process unnecessarily complex since the Manifest spec is written in Respec.)

In [steps for processing the src member of an image](https://www.w3.org/TR/appmanifest/#dfn-processing-the-src-member-of-an-image), there is "Otherwise, [parse](https://url.spec.whatwg.org/#concept-url-parser) *value* using *manifest URL* as the base URL and return the result." This needs to be generalized so the steps for processing takes a "base URL" parameter, which in the case of the manifest is the manifest URL, and in the case of being invoked from a document, is the document URL.

**Another aside**: Aha, @aarongustafson I just realised why your other PR had the separate steps for processing the URL of the shortcut info; it was copied from this ImageResource steps! Yeah, these steps are way too verbose; there is no need to do manual type checking on the URL or have separate steps for this. I'll put a PR (on the Manifest spec) to simplify it.

**Comment by jakearchibald** [comment]
> The user agent and/or OS should be free to pick "the best" icon from the set, and that could mean different things in different contexts.

When I'm writing things like this, I often think "does the order of these matter", and it's frustrating if the spec's answer is 🤷‍♀️

**Comment by rayankans** [comment]
> Any reason you're starting from scratch and not moving the text from the Manifest spec

It's mostly moved from the Manifest spec, but I'm of the opinion that Bikeshed removes of the unnecessary complexity of Respec :)

I've reworded a few things, and intentionally removed URL resolution. That's something that would be implicitly handled by the `fetch` algorithm.

**Comment by mgiuca** [comment]
> It's mostly moved from the Manifest spec, but I'm of the opinion that Bikeshed removes of the unnecessary complexity of Respec :)

We can bikeshed about Bikeshed vs Respec. Ultimately it doesn't really matter, but it seems kinda silly, given that you're splitting a spec into two pieces, to rewrite one of the pieces in a different language based on personal preference. Since the two specs will be tightly coupled, it increases the burden of working on the two specs side-by-side.

FWIW, Respec has one huge advantage over Bikeshed which is that you do not need to download, set up, and run a compile step every time you change it, nor do you need to manually check the .html file into the repo and make sure you keep it up to date whenever you commit changes. To me, that drastically outweighs any quibbles about having to write HTML versus another markup language.

> I've reworded a few things, and intentionally removed URL resolution. That's something that would be implicitly handled by the `fetch` algorithm.

How would the fetch algorithm know to resolve the URL against the manifest URL (or whichever other base URL the client wants to use, for non-manifest clients)? Right now, the Image Resource spec doesn't have the [Fetching image resources](https://www.w3.org/TR/appmanifest/#fetching-image-resources) algorithm outlined in Manifest, which gives details on how to use the fetch algorithm to get an image resource. The Image Resource spec just says "The src of an ImageResource is a string from which a user agent can create a request's URL to fetch the image’s data." The "fetch" algorithm takes a request, and you don't say how to make that request.

The [fetch algorithm](https://fetch.spec.whatwg.org/#concept-fetch) doesn't resolve URLs against any base URL, because it expects a full Request object to be given. The [`Request` constructor](https://fetch.spec.whatwg.org/#dom-request) (and by extension, the [`fetch` method](https://fetch.spec.whatwg.org/#dom-global-fetch)) does resolve the URL against a base URL, but 1. you aren't using that method, and 2. that says "Let baseURL be current settings object’s API base URL." --- in the manifest context, there is no "current settings object" because we aren't in a JavaScript environment. So you need to explicitly perform URL resolution.

**Comment by mgiuca** [comment]
> When I'm writing things like this, I often think "does the order of these matter", and it's frustrating if the spec's answer is 🤷‍♀️

Due to what I said above (the selection algorithm is often implemented by the OS, not the UA), we can't make the order not matter. For example, you take all the icons and put them in an .ico file on Windows. Windows probably has a selection algorithm that cares about order. We can't really make any statements about _how_ it cares about the order: some OS might be biased towards earlier icons, another might be biased towards later. I can't think of any text we could really put in here regarding the order of icons that UAs delegating to the OS could reliably implement.

Is there any meaningful action you could take as a developer w.r.t. ordering your icons where it would help if you knew the ordering rules?

**Comment by marcoscaceres** [comment]
About ordering, I think best we can do would be to add a note that describes what an OS might do (based on what @mgiuca said above). 

As an aside, I'd also like second what @mgiuca said above: I think our expectation was that this spec would initially be a copy/paste of what's in the web manifest spec, can we would refine from there... keeping in the current (ReSpec) format makes it much easier for us already involved with the Manifest spec to contribute to this spec. Note also that ReSpec supports most of the same shorthands as BikeShed, so that should address the complexity issue - happy to help with those.

**Comment by rayankans** [comment]
About resolving the URL, this ties into issue #5. I've excluded the algorithm of fetching a resource from the spec since every spec will want to handle it differently. It's also a very simple algorithm (Create request -> Fetch request), but the way the Request options will vary from spec to spec.

The Manifest spec has a very specific way of resolving the image URL (using the base URL from the Manifest URL), so that should live in the Manifest spec. We could add a generalized algorithm that takes a baseURL to resolve the image URL, but that would be overkill.

Since this seems to be the general consensus, I'll move the spec over to ReSpec.

**Comment by mgiuca** [comment]
> We could add a generalized algorithm that takes a baseURL to resolve the image URL, but that would be overkill.

I don't see that as overkill. I think it's necessary. The Image Resource spec should include a copy of [processing an array of image resources](https://www.w3.org/TR/appmanifest/#processing-an-array-of-image-resources) from the Manifest spec. (As I just looked, it has some obvious errors, which I'm happy to fix up either before or after it's copied.)

Literally the only change required (apart from fixing errors) is to rename "*manifest URL*" to "*base URL*" throughout that section. The manifest would pass the manifest URL as the *base URL*, other specs would pass the document URL.

> Since this seems to be the general consensus, I'll move the spec over to ReSpec.

Thankyou, that will help a lot with working between the two specs.

**Comment by aarongustafson** [comment]
@marcoscaceres Any word on whether we need to adjust the Web Apps charter to account for this being broken off into its own spec?

**Comment by aarongustafson** [comment]
PR inbound.

**Comment by aarongustafson** [comment]
Drafted a note about order mattering (within the context of the array processing):

> The choice of what to do with the Array&lt;<a>ImageResource</a>&gt;  returned from this algorithm is left to the implementation context in which it is being used. Regardless of the implementation context, however, the order of the <a>ImageResource</a> members provided MUST be the order in which they are returned. This will enable each implementation context to consider the order of the <a>ImageResource</a> members provided by the author in their  selection algorithm, should they so choose.

Can we have a MUST in a note? Should this be normal text instead?

**Comment by mgiuca** [comment]
Sorry for late reply.

The above paragraph didn't make it into the document did it?

> Can we have a MUST in a note? Should this be normal text instead?

No, you can't have an [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) term ("MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL") in a non-normative section or note, because then you would be putting a normative requirement in what is supposedly a non-normative sentence. (I've been told explicitly to even avoid using these words non-capitalized in their colloquial meaning, as it adds confusion about whether it's a requirement or not. The one that trips me up is that I tend to use "should" informally; I've been told to replace it with the rather clunky "will want to". Similarly, use "might" instead of "may".)

In this case, however, it sounds like you are actually trying to create a normative requirement, so that paragraph should be in a normative section.
